### ISSUE TITLE
Ошибка генерации проекта при парсинге cookiecutter.json

### ISSUE THREAD

**Issue by dadyarri** [dadyarri/lab-work-template#1]
`cookiecutter gh:dadyarri/lab-work-template` на windows в cmd кидает ошибку `JSONDecodeError` при попытке распарсить cookiecutter.json

**Comment by nibezo** [comment]
Traceback ошибки: 

C:\Users\nibezo\Desktop\Python\lab-work-template>cookiecutter gh:dadyarri/lab-work-template
Traceback (most recent call last):
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\generate.py", line 91, in generate_context
    obj = json.load(file_handle, object_pairs_hook=OrderedDict)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 548: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nibezo\AppData\Local\Programs\Python\Python39\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\cli.py", line 140, in main
    cookiecutter(
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\main.py", line 85, in cookiecutter
    context = generate_context(
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\generate.py", line 101, in generate_context
    raise ContextDecodingException(our_exc_message)
cookiecutter.exceptions.ContextDecodingException: JSON decoding error while loading "C:\Users\nibezo\.cookiecutters\lab-work-template\cookiecutter.json".  Decoding error details: "'charmap' codec can't decode byte 0x98 in position 548:
 character maps to <undefined>"

**Comment by dadyarri** [comment]
cookiecutter/cookiecutter#1533

**Comment by dadyarri** [comment]
TODO: попробовать убрать символ `|` из файла с тестами

**Comment by dadyarri** [comment]
Фиксится установкой cookiecutter из github
`pip install git+https://github.com/cookiecutter/cookiecutter`
